### ISSUE TITLE
doesnt work yet?

### ISSUE THREAD

**Issue by ChrisNML** [jasonwynn10/WorldShift#1]
The server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA3 for Minecraft: PE v1.0.0.16 (protocol version 100)

Plugin Version: Build 4

the plugin doesnt seem to work

**Comment by jasonwynn10** [comment]
I haven't updated it to the latest PocketMine alpha yet

**Comment by ChrisNML** [comment]
Im sorry i didnt see the notification until you closed it, there is no error, ecxcept it says not loaded, how would you load another world

**Comment by jasonwynn10** [comment]
please test the latest version

**Comment by NML32** [comment]
Yes, we are running the latest version from commit 2e539f818f657930e4f7f717548da2b80d89f1ca
Only the currently loaded world is listed non of the other worlds are displayed.

![capture](https://cloud.githubusercontent.com/assets/6879399/22570940/87094c2c-e96b-11e6-9ac5-fadeaf2e294b.JPG)

![worldshift](https://cloud.githubusercontent.com/assets/6879399/22570910/6e62f65a-e96b-11e6-9805-7ea9d0fcff9d.JPG)

**Comment by NML32** [comment]
Worlds now load and once the world is loaded it shows up in the list.

**Comment by jasonwynn10** [comment]
that's how it should work
