### ISSUE TITLE
cannot use perm

### ISSUE THREAD

**Issue by epicslendyz** [jasonwynn10/WorldShift#2]
when ever i try to use /worlds it said i dont have perm, when i use /world it said "level isnt level"

**Comment by jasonwynn10** [comment]
you are saying two things here, what is the issue?

**Comment by epicslendyz** [comment]
worlds and world command dont work, worlds said "Level Isnt Level" . World said "You Dont Have the Permision to use this plugin"

**Comment by jasonwynn10** [comment]
That just means that you didn't put in one of the available level names. Please note that the names are CaSe sensitive. Also, if you need to be op to switch worlds.
